<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\ChargeController;

use App\Http\Controllers\Api\VehicleController;
use App\Http\Controllers\Api\ChargerController;
use App\Http\Controllers\Api\ChargersChargeController;
use App\Http\Controllers\Api\ChargerLocationController;
use App\Http\Controllers\Api\VehiclesChargeController;
use App\Http\Controllers\Api\VehiclesStateOfHealthController;
use App\Http\Controllers\Api\ChargerLocationsChargerController;
use App\Http\Controllers\Api\ChargerLocationsChargeController;
use App\Http\Controllers\Api\ChargerLocationsDiscountHomeChargingController;

/*
|--------------------------------------------------------------------------
| Api Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

Route::name('api.')
    ->prefix('api')
    ->group(function () {
        Route::post('/login', [AuthController::class, 'login'])->name(
            'api.login'
        );

        Route::middleware('auth:sanctum')->group(function () {
            Route::get('/charges', [ChargeController::class, 'index'])->name(
                'charges.index'
            );

            Route::post('/charges', [ChargeController::class, 'store'])->name(
                'charges.store'
            );

            Route::get('/charges/{charge}', [
                ChargeController::class,
                'show',
            ])->name('charges.show');

            Route::put('/charges/{charge}', [
                ChargeController::class,
                'update',
            ])->name('charges.update');

            Route::delete('/charges/{charge}', [
                ChargeController::class,
                'destroy',
            ])->name('charges.destroy');

            Route::get('/vehicles/{vehicle}/charges', [
                VehiclesChargeController::class,
                'index',
            ])->name('vehicles.charges.index');

            Route::post('/vehicles/{vehicle}/charges', [
                VehiclesChargeController::class,
                'store',
            ])->name('vehicles.charges.store');

            Route::get('/vehicles/{vehicle}/state-of-healths', [
                VehiclesStateOfHealthController::class,
                'index',
            ])->name('vehicles.state-of-healths.index');

            Route::post('/vehicles/{vehicle}/state-of-healths', [
                VehiclesStateOfHealthController::class,
                'store',
            ])->name('vehicles.state-of-healths.store');

            Route::get('/vehicles', [VehicleController::class, 'index'])->name(
                'vehicles.index'
            );

            Route::post('/vehicles', [VehicleController::class, 'store'])->name(
                'vehicles.store'
            );

            Route::get('/vehicles/{vehicle}', [
                VehicleController::class,
                'show',
            ])->name('vehicles.show');

            Route::put('/vehicles/{vehicle}', [
                VehicleController::class,
                'update',
            ])->name('vehicles.update');

            Route::delete('/vehicles/{vehicle}', [
                VehicleController::class,
                'destroy',
            ])->name('vehicles.destroy');

            Route::get('/charger-locations/{charger-location}/chargers', [
                ChargerLocationsChargerController::class,
                'index',
            ])->name('charger-locations.chargers.index');

            Route::post('/charger-locations/{charger-location}/chargers', [
                ChargerLocationsChargerController::class,
                'store',
            ])->name('charger-locations.chargers.store');

            Route::get('/charger-locations', [
                ChargerLocationController::class,
                'index',
            ])->name('charger-locations.index');

            Route::post('/charger-locations', [
                ChargerLocationController::class,
                'store',
            ])->name('charger-locations.store');

            Route::get('/charger-locations/{chargerLocation}', [
                ChargerLocationController::class,
                'show',
            ])->name('charger-locations.show');

            Route::put('/charger-locations/{chargerLocation}', [
                ChargerLocationController::class,
                'update',
            ])->name('charger-locations.update');

            Route::delete('/charger-locations/{chargerLocation}', [
                ChargerLocationController::class,
                'destroy',
            ])->name('charger-locations.destroy');

            Route::get('/chargers', [ChargerController::class, 'index'])->name(
                'chargers.index'
            );

            Route::post('/chargers', [ChargerController::class, 'store'])->name(
                'chargers.store'
            );

            Route::get('/chargers/{charger}', [
                ChargerController::class,
                'show',
            ])->name('chargers.show');

            Route::put('/chargers/{charger}', [
                ChargerController::class,
                'update',
            ])->name('chargers.update');

            Route::delete('/chargers/{charger}', [
                ChargerController::class,
                'destroy',
            ])->name('chargers.destroy');
        });
    });
